// Generate app/components/Wall/stars.ts from the HYG star database.
//
// Source: astronexus/HYG-Database, hyg/CURRENT/hygdata_v41.csv (Hipparcos + Yale BSC
// + Gliese). Download once:
//   curl -L -o hyg.csv https://raw.githubusercontent.com/astronexus/HYG-Database/main/hyg/CURRENT/hygdata_v41.csv
// Then:  node scripts/gen-stars.mjs <path-to-hyg.csv> [magLimit]
//
// Output rows are [x, y, b, c]:
//   x,y : equirectangular RA/Dec normalized 0..1  (x = ra/24h, y = (dec+90)/180°)
//   b   : brightness 0..1, linear in magnitude (brightest star → 1)
//   c   : B-V colour index quantised to 0..63 (Starfield expands it to an RGB via a
//         pre-computed black-body palette). Keeps the file compact while carrying real
//         stellar colour (blue-white O/B → white A → yellow G → orange-red K/M).
import fs from "node:fs";

const SRC = process.argv[2];
const MAG_LIMIT = parseFloat(process.argv[3] ?? "7.6");
if (!SRC) {
  console.error("usage: node scripts/gen-stars.mjs <hyg.csv> [magLimit]");
  process.exit(1);
}

const CI_MIN = -0.4;
const CI_MAX = 2.0;
const CI_STEPS = 63;

const lines = fs.readFileSync(SRC, "utf8").split("\n");
const head = lines[0].split(",").map((s) => s.replace(/"/g, ""));
const iRa = head.indexOf("ra");
const iDec = head.indexOf("dec");
const iMag = head.indexOf("mag");
const iCi = head.indexOf("ci");
const iProper = head.indexOf("proper");

const rows = [];
let minMag = Infinity;
let maxMag = -Infinity;
for (let i = 1; i < lines.length; i++) {
  const c = lines[i].split(",");
  if (c.length <= iCi) continue;
  if (c[iProper] === "Sol") continue; // skip the Sun (HYG id 0)
  const ra = parseFloat(c[iRa]);
  const dec = parseFloat(c[iDec]);
  const mag = parseFloat(c[iMag]);
  if (!Number.isFinite(ra) || !Number.isFinite(dec) || !Number.isFinite(mag)) continue;
  if (mag > MAG_LIMIT) continue;
  let ci = parseFloat(c[iCi]);
  if (!Number.isFinite(ci)) ci = 0.6; // default to a sun-like yellow-white
  rows.push({ ra, dec, mag, ci });
  if (mag < minMag) minMag = mag;
  if (mag > maxMag) maxMag = mag;
}

const span = maxMag - minMag || 1;
const out = rows.map((r) => {
  const x = +(r.ra / 24).toFixed(4);
  const y = +((r.dec + 90) / 180).toFixed(4);
  const b = +((maxMag - r.mag) / span).toFixed(3); // 0..1, brighter → larger
  const ciClamped = Math.max(CI_MIN, Math.min(CI_MAX, r.ci));
  const cIdx = Math.round(((ciClamped - CI_MIN) / (CI_MAX - CI_MIN)) * CI_STEPS);
  return `[${x},${y},${b},${cIdx}]`;
});

const body = `// Real stars — HYG v4.1 (Hipparcos + Yale BSC + Gliese), visual magnitude ≤ ${MAG_LIMIT}.
// ${out.length} stars. Each entry is [x, y, b, c]:
//   x/y : equirectangular RA/Dec projection normalized 0..1
//   b   : brightness 0..1 (linear in magnitude)
//   c   : B-V colour index quantised 0..${CI_STEPS} (Starfield maps it to an RGB)
// Generated by scripts/gen-stars.mjs from astronexus/HYG-Database — do not edit by hand.
/* eslint-disable */
export const STARS: ReadonlyArray<readonly [number, number, number, number]> = [${out.join(",")}];
`;

const dest = new URL("../app/components/Wall/stars.ts", import.meta.url);
fs.writeFileSync(dest, body);
console.log(`wrote ${out.length} stars (mag ≤ ${MAG_LIMIT}), ${(body.length / 1024).toFixed(0)} KB`);
