#!/usr/bin/env bash
set -euo pipefail

ROOT_DOCS_DIR="../docs"
OUT_DIR="./out"
APPCAST_FROM_BUILD="../build/appcast.xml"
RELEASE_NOTES_FROM_BUILD_DIR="../build/release-notes"
RELEASE_NOTES_PATH_IN_DOCS="release-notes"

die() {
  echo "Error: $*" >&2
  exit 1
}

info() {
  echo "[publish-docs] $*"
}

[[ -d "$OUT_DIR" ]] || die "Missing Next export output directory: $OUT_DIR (did next build produce it?)"
[[ -d "$ROOT_DOCS_DIR" ]] || die "Missing docs directory: $ROOT_DOCS_DIR"

tmp_dir="$(mktemp -d -t mos-docs-publish.XXXXXX)"
cleanup() { rm -rf "$tmp_dir"; }
trap cleanup EXIT

appcast_tmp="$tmp_dir/appcast.xml"
release_notes_tmp="$tmp_dir/release-notes"
mkdir -p "$release_notes_tmp"

# Prefer appcast generated by build/appcast.xml; otherwise preserve existing docs/appcast.xml.
if [[ -f "$APPCAST_FROM_BUILD" ]]; then
  cp "$APPCAST_FROM_BUILD" "$appcast_tmp"
elif [[ -f "$ROOT_DOCS_DIR/appcast.xml" ]]; then
  cp "$ROOT_DOCS_DIR/appcast.xml" "$appcast_tmp"
fi

# Preserve existing docs release notes, then overlay build release notes (newer wins on filename conflict).
if [[ -d "$ROOT_DOCS_DIR/$RELEASE_NOTES_PATH_IN_DOCS" ]]; then
  cp -R "$ROOT_DOCS_DIR/$RELEASE_NOTES_PATH_IN_DOCS/." "$release_notes_tmp/" || true
fi
if [[ -d "$RELEASE_NOTES_FROM_BUILD_DIR" ]]; then
  cp -R "$RELEASE_NOTES_FROM_BUILD_DIR/." "$release_notes_tmp/" || true
fi

info "Clearing $ROOT_DOCS_DIR"
rm -rf "$ROOT_DOCS_DIR"/*

info "Publishing $OUT_DIR -> $ROOT_DOCS_DIR"
mv "$OUT_DIR"/* "$ROOT_DOCS_DIR"

if [[ -f "CNAME" ]]; then
  cp "CNAME" "$ROOT_DOCS_DIR/"
fi
touch "$ROOT_DOCS_DIR/.nojekyll"

if [[ -f "$appcast_tmp" ]]; then
  mv "$appcast_tmp" "$ROOT_DOCS_DIR/appcast.xml"
  info "Restored appcast.xml"
fi

if [[ -n "$(ls -A "$release_notes_tmp" 2>/dev/null || true)" ]]; then
  mkdir -p "$ROOT_DOCS_DIR/$RELEASE_NOTES_PATH_IN_DOCS"
  cp -R "$release_notes_tmp/." "$ROOT_DOCS_DIR/$RELEASE_NOTES_PATH_IN_DOCS/"
  info "Restored release notes"
fi

info "Done"

